<!DOCTYPE html>
<html>
<head>
  <title></title>
<!-- Inline Styles -->
  <style>
    html, body {
      margin: 0px;
      padding: 0px;
      width: 100%;
      height: 100%;
      overflow: hidden;
    }
  </style>
  <!-- /Inline Styles -->
  <script src="https://api.apiary.io/seeds/embed.js"></script>
</head>
<body>
 <script>
 try {
    var xmlHttp = null;
    xmlHttp = new XMLHttpRequest();
    xmlHttp.open("GET", window.location.href, false);
    xmlHttp.setRequestHeader('Accept', 'text/vnd.apiblueprint+markdown');
    xmlHttp.send(null);
    var markdown =  xmlHttp.responseText;
    var embed = new Apiary.Embed({
      apiBlueprint: markdown
    });
  }
  catch(err) {
    alert('We are sorry, but documentation rendering failed. Please try it again and if situation repeats, please let us know.');
  }
  </script>
</body>
</html>
